name: 'Validate an MG mod'
description: 'Validate an MG mod'
inputs:
  name:
    description: "name of the mod"
    required: true
    default: ''
  version:
    description: "mod version"
    required: true
    default: ''
  directory:
    description: "relative path to the directory containing the top-level mod xml file"
    required: false
    default: '.'
  type:
    description: "tech, scenario, or tileset"
    required: true
    default: tech
  remove_from_mod:
    description: "list of files or directories to remove, each separated by a space"
    required: false
    default: ''
  fail_on_warning:
    description: "Fail if no errors present, but warnings are indicated"
    required: false
    default: 'no'

runs:
  using: docker
  image: Dockerfile

branding:
  icon: package
  color: gray-dark
