name: 'Validate an MG mod'
description: 'Validate an MG mod'
inputs:
  name:
    description: "name of the mod"
    required: true
    default: ''
  release_name:
    description: "Specify if the name of your mod is different for releases"
    required: false
    default: ''
  directory:
    description: "relative path to the directory containing the top-level mod xml file"
    required: false
    default: '.'
  type:
    description: "tech, scenario, or tileset"
    required: true
    default: tech
  fail_on_warning:
    description: "Fail if no errors present, but warnings are indicated"
    required: false
    default: 'no'

runs:
  using: docker
  image: Dockerfile

branding:
  icon: package
  color: gray-dark
