name: Test Action

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  test-megaglest-data:
    runs-on: ubuntu-latest
    env:
      MOD_NAME: megalgest-data
      MOD_VERSION: ${{ github.sha }}
    steps:
    # # - name: clone MegaGlest data repo
    # #   run: cd test && git clone --depth 1 https://github.com/megaglest/megaglest-data
    # - uses: megaglest/gh-action-validate-megaglest-mod@v1 # test from last release
    #   with:
    #     name: ${{ env.MOD_NAME }}
    #     version: ${{ env.MOD_VERSION }}
    #     directory: 'test/${{ env.MOD_NAME }}'
    # - run: rm -rf /output/*
    # - name: clone MG Data
    #   run: git clone --depth 1 <mg data repo> or curl mg data last release archive
    - uses: actions/checkout@v3
    - name: Use action from self
      uses: ./
      with:
        name: ${{ env.MOD_NAME }}
        version: ${{ env.MOD_VERSION }}
        directory: 'test/${{ env.MOD_NAME }}'
