name: Test Action

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  test-megaglest-mod:
    runs-on: ubuntu-latest
    env:
      TEST_MOD_NAME: 'readypack-testing'
    steps:
    - uses: actions/checkout@v3
    - name: clone mod
      run: git clone --depth 1 https://github.com/zetaglest/${{ env.TEST_MOD_NAME }} test
    - name: Use action from self
      uses: ./
      with:
        name: ${{ env.TEST_MOD_NAME }}
        directory: test
        type: tech
        fail_on_warning: no
