name: Test Action

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  test-megaglest-techtree:
    runs-on: ubuntu-latest
    env:
      TEST_MOD_NAME: 'megapack'
    steps:
    - uses: actions/checkout@v3 # clones this repo
    - uses: actions/checkout@v3 # clones dependency
      with:
        clean: 'false'
        repository: 'megaglest/megaglest-data'
        path: 'megaglest-data'
        sparse-checkout: 'techs/megapack'
    - name: Use action from self
      uses: ./
      with:
        name: ${{ env.TEST_MOD_NAME }}
        directory: megaglest-data/techs/megapack
        type: tech
        fail_on_warning: no

  test-megaglest-scenario:
    runs-on: ubuntu-latest
    env:
      TEST_MOD_NAME: 'amazones'
    steps:
    - uses: actions/checkout@v3 # clones this repo
    - uses: actions/checkout@v3
      with:
        clean: 'false'
        repository: 'megaglest/megaglest-data'
        path: megaglest-data
        sparse-checkout: |
          scenarios/amazones
          techs/megapack
    - name:
      run: |
        mv megaglest-data/techs/megapack $GITHUB_WORKSPACE
        rm -rf $GITHUB_WORKSPACE/megaglest-data/techs
        cd $GITHUB_WORKSPACE
    - name: Use action from self
      uses: ./
      with:
        name: ${{ env.TEST_MOD_NAME }}
        directory: megaglest-data/scenarios/amazones
        type: scenario
        fail_on_warning: no
        dependencies: 'megapack'
