name: Test Action

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  test-megaglest-techtree:
    runs-on: ubuntu-latest
    env:
      TEST_MOD_NAME: 'readypack-testing'
    steps:
    - uses: actions/checkout@v3
    - name: clone mod
      run: git clone --depth 1 https://github.com/zetaglest/${{ env.TEST_MOD_NAME }} test
    - name: Use action from self
      uses: ./
      with:
        name: ${{ env.TEST_MOD_NAME }}
        directory: test
        type: tech
        fail_on_warning: no

  test-megaglest-scenario:
    runs-on: ubuntu-latest
    env:
      TEST_MOD_NAME: 'egypt_has_fallen'
    steps:
    - uses: actions/checkout@v3
    - name: clone scenario
      run: |
        git clone --depth 1 https://github.com/zetaglest/${{ env.TEST_MOD_NAME }} test
        # get only the megapack techtree
        git clone -n --depth=1 --filter=tree:0 https://github.com/megaglest/megaglest-data
        cd megaglest-data
        git sparse-checkout set --no-cone techs/megapack
        git checkout
        mv techs/megapack $GITHUB_WORKSPACE
        rm -rf $GITHUB_WORKSPACE/megaglest-data
        cd $GITHUB_WORKSPACE
    - name: Use action from self
      uses: ./
      with:
        name: ${{ env.TEST_MOD_NAME }}
        directory: test
        type: scenario
        fail_on_warning: no
        dependencies: 'megapack'
